# Site settings
title: RJ Fox Automotive
email: contact@rjfoxautomotive.com
phone: "+13524366133"
phone_display: "(352) 436-6133"
address: "801 David Walker Dr, Eustis, FL 32726"
owner: "Rob"
description: "Premier Auto Repair Shop in Eustis, FL. Owned and operated by Rob."
baseurl: "" # Leave empty for root domain

# Build settings
markdown: kramdown
permalink: pretty
permalink: /:year/:month/:day/:title/



