# Site settings
title: RJ Fox Automotive
email: contact@rjfoxautomotive.com
phone: "+13522503210"
phone_display: "(352) 250-3210"
address: "801 David Walker Dr, Eustis, FL 32726"
owner: "Rob"
description: "Premier Auto Repair Shop in Eustis, FL. Owned and operated by Rob."
baseurl: "/"

# Build settings
markdown: kramdown
permalink: pretty
permalink: /:year/:month/:day/:title/
# Enable Liquid processing in markdown files
kramdown:
  parse_block_html: true


